export enum SUPPORTED_CHAINS_IDS {
  ETHEREUM_MAINNET = 1,
  POLYGON_MAINNET = 137,
  BASE_SEPOLIA = 84532,
  POLYGON_AMOY = 80002,
  ARBITRUM_ONE = 42161,
}
export enum SUPPORTED_TOKENS {
  USDC = "USDC",
  DAI = "DAI",
  ETH = "ETH",
}
